base:
  # 启用书源 (只能选一个，当前可选值：1、2、3)
  source-id: 3
  # 下载路径，绝对相对均可 (Windows 路径分隔符不要用 \ ，用 / 或 \)
  download-path: "downloads"
  # 文件扩展名，支持 txt, epub, 推荐 epub
  extname: "epub"
  # 启动时是否自动更新 (1 开，0 关)
  auto-update: 1
  # 日志级别,默认 error (panic fatal error warn info debug trace)
  log-level: error

crawl:
  # 爬取线程数，-1 表示自动设置
  threads: -1

retry:
  # 最大重试次数 (针对首次下载失败的章节)
  max-attempts: 3