base:
  # 启用书源 (只能选一个, 当前可选值：1、2、3)
  source-id: 3
  # 下载路径, 绝对相对均可 (Windows 路径分隔符不要用 \ , 用 / 或 \)
  download-path: "downloads"
  # 文件扩展名, 支持 txt, epub, 推荐 epub
  extname: "epub"
  # 日志级别,默认 error (panic fatal error warn info debug trace)
  log-level: error

crawl:
  # 爬取线程数, -1 表示自动设置
  threads: -1

retry:
  # 最大重试次数 (针对首次下载失败的章节)
  max-attempts: 3

 # 聊天机器人, 目前只提供 ollama
chatbot:
  # 模型选择：根据自己电脑配置来：至少有 8 GB 的 RAM 来运行 7B 型号，16 GB 的 RAM 来运行 13B 的型号，32 GB 的 RAM 来运行 33B 型号
  model: "llama2"