// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CheckUpdate():Promise<string>;

export function DownLoadNovel(arg1:model.SearchResult):Promise<model.CrawlResult>;

export function GetConfig():Promise<model.GetConfigResult>;

export function GetDownloadProgress(arg1:model.SearchResult):Promise<model.ProgressResult>;

export function GetUsageInfo():Promise<Array<string>>;

export function SerachNovel(arg1:string):Promise<Array<model.SearchResult>>;
