// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function DownLoadNovel(arg1) {
  return window['go']['main']['App']['DownLoadNovel'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDownloadProgress() {
  return window['go']['main']['App']['GetDownloadProgress']();
}

export function GetUsageInfo() {
  return window['go']['main']['App']['GetUsageInfo']();
}

export function SerachNovel(arg1) {
  return window['go']['main']['App']['SerachNovel'](arg1);
}
