// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownLoadNovel(arg1) {
  return window['go']['main']['App']['DownLoadNovel'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDownloadProgress(arg1) {
  return window['go']['main']['App']['GetDownloadProgress'](arg1);
}

export function GetUpdateInfo() {
  return window['go']['main']['App']['GetUpdateInfo']();
}

export function GetUsageInfo() {
  return window['go']['main']['App']['GetUsageInfo']();
}

export function SerachNovel(arg1) {
  return window['go']['main']['App']['SerachNovel'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}
